import { chromium } from "playwright";
const OUT = "/tmp/claude-0/-home-user-Saas-fitness/aa49840f-4bae-5a6f-a506-cae875d937d3/scratchpad";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const p = await (await b.newContext({ viewport: { width: 390, height: 844 }, isMobile: true })).newPage();
const errs = [];
p.on("pageerror", (e) => errs.push(e.message));
await p.goto("http://localhost:3100/exercices", { waitUntil: "networkidle" });
const t = await p.locator("body").innerText();
console.log("titre :", t.split("\n").find((l) => /exercices, rangés/.test(l)));
const over = await p.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
console.log("débordement horizontal :", over, "px");
await p.screenshot({ path: `${OUT}/C-catalogue.png`, fullPage: false });
await p.evaluate(() => window.scrollTo(0, 900));
await p.waitForTimeout(300);
await p.screenshot({ path: `${OUT}/C-catalogue2.png` });
console.log("erreurs :", errs.length ? errs : "aucune");
await b.close();
